### ISSUE TITLE
plugin approvals

### ISSUE THREAD

**Issue by NyakudyaA** [dayjournal/qgis-japanelevation-plugin#1]
@dayjournal  Can you please let us know what has changed in version 2. We need a changelog example:
* Port to QGIS3

**Comment by dayjournal** [comment]
The plugin itself has not changed.
It corresponds to QGIS 3.0.

QGIS2 Repository
https://github.com/dayjournal/JapanElevation/tree/QGIS2

**Comment by dayjournal** [comment]
Should I separate the QGIS Python Plugins Repository by version and register?

**Comment by NyakudyaA** [comment]
@dayjournal  you do not need to separate anything. What I meant is that you should just have a changelog that describes what is new in this version. 
So in this instance, there are no new features except that it now supports QG3

**Comment by dayjournal** [comment]
- The new in this version is to correspond to QGIS 3.

I added it in changelog.

**Comment by NyakudyaA** [comment]
thanks will approve now
