### ISSUE TITLE
TypeError: 'QVariant' object is not subscriptable

### ISSUE THREAD

**Issue by ghost** [dayjournal/qgis-japanelevation-plugin#2]
Hej,

I am trying to install JapanElevation plugin on qGIS 3.6.0. but receiving this error: 

Couldn't load plugin 'JapanElevation' due to an error when calling its classFactory() method 

TypeError: 'QVariant' object is not subscriptable 
Traceback (most recent call last):
  File "C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python\qgis\utils.py", line 335, in startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\JapanElevation\__init__.py", line 19, in classFactory
    return JapanElevation(iface)
  File "C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\JapanElevation\JapanElevation.py", line 40, in __init__
    locale = QSettings().value('locale/userLocale')[0:2]
TypeError: 'QVariant' object is not subscriptable

Python version: 3.7.0 (v3.7.0:1bf9cc5093, Jun 27 2018, 04:59:51) [MSC v.1914 64 bit (AMD64)] 
QGIS version: 3.6.0-Noosa Noosa, 58734527ab 

Python Path:
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python
C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins
C:/PROGRA~1/QGIS3~1.6/apps/qgis/./python/plugins
C:\Program Files\QGIS 3.6\bin\python37.zip
C:\PROGRA~1\QGIS3~1.6\apps\Python37\DLLs
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib
C:\Program Files\QGIS 3.6\bin
C:\PROGRA~1\QGIS3~1.6\apps\Python37
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\win32\lib
C:\PROGRA~1\QGIS3~1.6\apps\Python37\lib\site-packages\Pythonwin
C:/Users/manuel/AppData/Roaming/QGIS/QGIS3\profiles\default/python
C:\Users\manuel\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins
C:\Users\manuel\AppData\Roaming\QGIS\QGIS3\profiles\default\python\plugins

**Comment by dayjournal** [comment]
It works fine in my environment. QGIS 3.6.1
Try reinstalling the plugin.
